print("Calcular el area de un cuadrado")
bas=float(input("Inserte por favor la medida de la base "))
alt=float(input("Inserte el valor de la altura "))
area=float(bas*alt)
print("El area del triangulo es: ",area)
input()
